all:
	typst compile curriculum_vitae.typ \
		--font-path "/Users/adarsh/Library/Application Support/Adobe/CoreSync/plugins/livetype/.r"

# For live previewing
watch:
	typst watch curriculum_vitae.typ \
		--font-path "/Users/adarsh/Library/Application Support/Adobe/CoreSync/plugins/livetype/.r"

clean:
	rm curriculum_vitae.pdf
